<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        // Ubah kolom id dari GENERATED ALWAYS menjadi GENERATED BY DEFAULT
        DB::statement('ALTER TABLE kategori ALTER COLUMN id SET GENERATED BY DEFAULT');
    }

    public function down(): void
    {
        DB::statement('ALTER TABLE kategori ALTER COLUMN id SET GENERATED ALWAYS');
    }
};